name: Deploy Webhook

on:
  repository_dispatch:
    types:
      - deploy-production
      - deploy-develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Create local changes
        run: |
          echo "git commit --allow-empty -m 'Deploy Production' "
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event.action == 'deploy-production' && 'main' || 'develop' }}
          empty: true
          force: true
          message: "Deploy Production"
